name: CI

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install SDL2 development files (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --yes libsdl2-dev
      - run: mise run setup
      - run: mise run check
      - run: mise run build
